#+TITLE: 树莓派运行 Elasticsearch 生产模式
#+AUTHOR: 陳放為


* TLDR
结论，树莓派能运行 Elasticsearch， 不论单点模式还是生产模式，都能运行且不用进行特别的操作。但是从使用上来讲，运行在树莓派上 Elasticsearch 基本上不能用，太卡太慢了，我把树莓派上的 Elasticsearch 加入到 es 集群上，直接把一些搜索给卡死。本文只是记录如何在树莓派上把 es 跑起来，如果真的想用，建议还是用别的机器把。

#+BEGIN_QUOTE
注：我用的树莓派型号是 3B
#+END_QUOTE

* 我当初为什么想在树莓派上运行 Elasticsearch
当时我在家里的网络环境中搭建了一个 Elasticsearch，但是计算资源不多，想在自己用也用不了多少，树莓派比较省电，运行一个 Elasticsearch 节点，能用的话就美滋滋。二来，单节点的 Elasticsearch 的健康程度总是 yellow，我有一点点强迫症，如果多节点的 es 集群能把它变绿，那是最好。

* 部署

我先在 google 上搜索了一番，有一篇文章是通过 =apt= 来安装，那我先试一下


#+BEGIN_SRC bash
apt install elasticsearch

service start elasticsearch
#+END_SRC

但是却没有任何反应，修改了配置也不行，那算了，不用这个了，搞不好版本也不对，直接下载官方包吧。

** 直接下载官方包

在 [[https://www.elastic.co/downloads/elasticsearch]] 这个官方下载地址上，下载 [MACOS/LINUXsha] 这个 tar 包。

解压，然后更改配置 =config/elasticsearch.yml= 

加上 =discovery.type=single-node= 这一句配置

出乎我的想象，这货很顺利的跑起来了，只是需要加上 =-Xms512m -Xmx512m= 这个 jvm 设置，虽然树莓派有 1G 内存，但是高于 512 真的跑不起来。

结果。。

结果很成功啊，=elasticsearch= 启动了起来，虽然有点慢，但是还是在 rpi:9200 看到熟悉的 json 


#+BEGIN_SRC json
{
  "name" : "raspberry",
  "cluster_uuid" : "C7W9Y8dRTGSwThnH7YaM8w",
  "version" : {
    "number" : "6.6.1",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "1fd8f69",
    "build_date" : "2019-02-13T17:10:04.160291Z",
    "build_snapshot" : false,
    "lucene_version" : "7.6.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
#+END_SRC


** 生产模式节点
嗯，单节点的开发模式起来，让我看到了希望（说真的我当时希望还真的不大，树莓派的性能真的很差，而 elasticsearch 出了名耗内存）

我的目标是在运行生产模式，在 =config/elasticsearch.yml= 中把=discovery.type=single-node= 去掉

然后修改一系列配置


#+BEGIN_SRC bash
cluster.name: docker-cluster

network.host : 0.0.0.0

discovery.zen.ping.unicast.hosts: ["192.169.50.2"]
#+END_SRC

其中 =cluster.name= 是集群的名字，要和其它 es 部署实力一样

=network.host= 这个配置将 =es= 部署在 0.0.0.0, 不然默认是 127.0.0.1

然后就是 =discovery.zen.ping.unicast.hosts= 这个配置就是要写上其它节点的地址，可以是 ip，也可以是域名，也可以是 host。这是我填的是我另外 docker 母机的地址，但是导致一个问题，因为在我另外的一个节点是运行在 =docker= 中的，暴露了 =9200= 和 =9300= 给母鸡。

docker 母机机器的 ip 是 =172.17.0.6=，elasticsearch 大概会告诉其它节点它自己的 ip，所以树莓派上的 es 虽然通过 =192.169.50.2= 找到了节点，但是还是会报错，说找不到 =172.17.0.6= 这个地址

我细想了一下， 好像也没有别的办法，es 的可配置项也不多，唯有用 iptables 这个好用的神奇把出口 ip 改一下

遂用下面的命令在树莓派上的母鸡上一敲，问题迎刃而解


#+BEGIN_QUOTE
es 的 docker 镜像没有安装 iptables，不然直接在 docker 容器里面用 iptables 会更干净
#+END_QUOTE

#+BEGIN_SRC bash
iptables -t nat -A OUTPUT -d 172.17.0.6 -j DNAT --to-destination 192.169.50.2
#+END_SRC

** Server VM & system_call_filter 问题
用 iptables 把 ip 的问题解决了之后，又遇到了两个新的问题，原因是 es 运行生产模式之后，要强制运行 =bootstrap check= ，说白了就是运行环境要把单节点的开发模式严格，其中树莓派上遇到了两个

- Server VM
- system_call_filter

[[image-url:./树莓派运行 Elasticsearch 生产模式/8460377f7d2b454d3614554fc4493dd2]]

如图示，bootstrap check 报了两行错误

#+BEGIN_SRC bash
[2019-03-16T23:26:09,592][WARN ][o.e.b.Natives            ] [node-raspberry] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-armel/libjnidispatch.so) not found in resource path ([file:/home/pi/elasticsearch-6.6.2/lib/elasticsearch-core-6.6.2.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-misc-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/HdrHistogram-2.1.9.jar, file:/home/pi/elasticsearch-6.6.2/lib/plugin-classloader-6.6.2.jar, file:/home/pi/elasticsearch-6.6.2/lib/log4j-core-2.11.1.jar, file:/home/pi/elasticsearch-6.6.2/lib/t-digest-3.2.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-join-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/java-version-checker-6.6.2.jar, file:/home/pi/elasticsearch-6.6.2/lib/log4j-1.2-api-2.11.1.jar, file:/home/pi/elasticsearch-6.6.2/lib/elasticsearch-x-content-6.6.2.jar, file:/home/pi/elasticsearch-6.6.2/lib/spatial4j-0.7.jar, file:/home/pi/elasticsearch-6.6.2/lib/elasticsearch-launchers-6.6.2.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-memory-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/snakeyaml-1.17.jar, file:/home/pi/elasticsearch-6.6.2/lib/jopt-simple-5.0.2.jar, file:/home/pi/elasticsearch-6.6.2/lib/elasticsearch-cli-6.6.2.jar, file:/home/pi/elasticsearch-6.6.2/lib/elasticsearch-6.6.2.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-analyzers-common-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/jackson-core-2.8.11.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-spatial-extras-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/jts-core-1.15.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/jackson-dataformat-smile-2.8.11.jar, file:/home/pi/elasticsearch-6.6.2/lib/joda-time-2.10.1.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-grouping-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-suggest-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/log4j-api-2.11.1.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-spatial-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-queries-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-highlighter-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/jna-4.5.1.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-sandbox-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-queryparser-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-spatial3d-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/jackson-dataformat-yaml-2.8.11.jar, file:/home/pi/elasticsearch-6.6.2/lib/elasticsearch-secure-sm-6.6.2.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-core-7.6.0.jar, file:/home/pi/elasticsearch-6.6.2/lib/hppc-0.7.1.jar, file:/home/pi/elasticsearch-6.6.2/lib/jackson-dataformat-cbor-2.8.11.jar, file:/home/pi/elasticsearch-6.6.2/lib/lucene-backward-codecs-7.6.0.jar])
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at com.sun.jna.Native.<clinit>(Native.java:190) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_65]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_65]
	at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:102) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.6.2.jar:6.6.2]
[2019-03-16T23:26:09,652][WARN ][o.e.b.Natives            ] [node-raspberry] cannot check if running as root because JNA is not available
[2019-03-16T23:26:09,654][WARN ][o.e.b.Natives            ] [node-raspberry] cannot install system call filter because JNA is not available
[2019-03-16T23:26:09,657][WARN ][o.e.b.Natives            ] [node-raspberry] cannot register console handler because JNA is not available
[2019-03-16T23:26:09,668][WARN ][o.e.b.Natives            ] [node-raspberry] cannot getrlimit RLIMIT_NPROC because JNA is not available
[2019-03-16T23:26:09,670][WARN ][o.e.b.Natives            ] [node-raspberry] cannot getrlimit RLIMIT_AS because JNA is not available
[2019-03-16T23:26:09,671][WARN ][o.e.b.Natives            ] [node-raspberry] cannot getrlimit RLIMIT_FSIZE because JNA is not available
[2019-03-16T23:26:11,165][INFO ][o.e.e.NodeEnvironment    ] [node-raspberry] using [1] data paths, mounts [[/mnt/remote (192.168.50.1:/mnt/NTFS/Storage)]], net usable_space [28.4gb], net total_space [28.8gb], types [nfs]
[2019-03-16T23:26:11,167][INFO ][o.e.e.NodeEnvironment    ] [node-raspberry] heap size [505.6mb], compressed ordinary object pointers [unknown]
[2019-03-16T23:26:11,195][INFO ][o.e.n.Node               ] [node-raspberry] node name [node-raspberry], node ID [UEpNAPb5Rqyeeox4J1d1mQ]
[2019-03-16T23:26:11,197][INFO ][o.e.n.Node               ] [node-raspberry] version[6.6.2], pid[2642], build[default/zip/3bd3e59/2019-03-06T15:16:26.864148Z], OS[Linux/4.14.34-v7+/arm], JVM[Oracle Corporation/Java HotSpot(TM) Client VM/1.8.0_65/25.65-b01]
[2019-03-16T23:26:11,199][INFO ][o.e.n.Node               ] [node-raspberry] JVM arguments [-Xms512m, -Xmx512m, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-6488336661512980697, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Des.path.home=/home/pi/elasticsearch-6.6.2, -Des.path.conf=/home/pi/elasticsearch-6.6.2/config, -Des.distribution.flavor=default, -Des.distribution.type=zip]
[2019-03-16T23:26:32,351][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [aggs-matrix-stats]
[2019-03-16T23:26:32,352][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [analysis-common]
[2019-03-16T23:26:32,353][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [ingest-common]
[2019-03-16T23:26:32,354][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [lang-expression]
[2019-03-16T23:26:32,355][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [lang-mustache]
[2019-03-16T23:26:32,355][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [lang-painless]
[2019-03-16T23:26:32,356][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [mapper-extras]
[2019-03-16T23:26:32,357][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [parent-join]
[2019-03-16T23:26:32,357][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [percolator]
[2019-03-16T23:26:32,358][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [rank-eval]
[2019-03-16T23:26:32,359][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [reindex]
[2019-03-16T23:26:32,360][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [repository-url]
[2019-03-16T23:26:32,360][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [transport-netty4]
[2019-03-16T23:26:32,361][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [tribe]
[2019-03-16T23:26:32,362][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-ccr]
[2019-03-16T23:26:32,363][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-core]
[2019-03-16T23:26:32,363][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-deprecation]
[2019-03-16T23:26:32,364][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-graph]
[2019-03-16T23:26:32,365][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-ilm]
[2019-03-16T23:26:32,366][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-logstash]
[2019-03-16T23:26:32,366][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-ml]
[2019-03-16T23:26:32,367][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-monitoring]
[2019-03-16T23:26:32,368][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-rollup]
[2019-03-16T23:26:32,368][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-security]
[2019-03-16T23:26:32,369][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-sql]
[2019-03-16T23:26:32,370][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-upgrade]
[2019-03-16T23:26:32,370][INFO ][o.e.p.PluginsService     ] [node-raspberry] loaded module [x-pack-watcher]
[2019-03-16T23:26:32,373][INFO ][o.e.p.PluginsService     ] [node-raspberry] no plugins loaded
[2019-03-16T23:27:19,653][INFO ][o.e.x.s.a.s.FileRolesStore] [node-raspberry] parsed [0] roles from file [/home/pi/elasticsearch-6.6.2/config/roles.yml]
[2019-03-16T23:27:26,306][DEBUG][o.e.a.ActionModule       ] [node-raspberry] Using REST wrapper from plugin org.elasticsearch.xpack.security.Security
[2019-03-16T23:27:28,211][INFO ][o.e.d.DiscoveryModule    ] [node-raspberry] using discovery type [zen] and host providers [settings]
[2019-03-16T23:27:34,468][INFO ][o.e.n.Node               ] [node-raspberry] initialized
[2019-03-16T23:27:34,470][INFO ][o.e.n.Node               ] [node-raspberry] starting ...
[2019-03-16T23:27:35,832][INFO ][o.e.t.TransportService   ] [node-raspberry] publish_address {172.17.0.1:9300}, bound_addresses {[::]:9300}
[2019-03-16T23:27:35,946][INFO ][o.e.b.BootstrapChecks    ] [node-raspberry] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [2] bootstrap checks failed
[1]: JVM is using the client VM [Java HotSpot(TM) Client VM] but should be using a server VM for the best performance
[2]: system call filters failed to install; check the logs and fix your configuration or disable system call filters at your own risk
[2019-03-16T23:27:36,012][INFO ][o.e.n.Node               ] [node-raspberry] stopping ...
[2019-03-16T23:27:36,087][INFO ][o.e.n.Node               ] [node-raspberry] stopped
[2019-03-16T23:27:36,088][INFO ][o.e.n.Node               ] [node-raspberry] closing ...
[2019-03-16T23:27:36,174][INFO ][o.e.n.Node               ] [node-raspberry] closed
#+END_SRC


*** 解决 system_call_filter

google 了一下，在 =config/elasticsearch.yml= 中加入一行配置即可解决


#+BEGIN_QUOTE yaml
bootstrap.system_call_filter: false
#+END_QUOTE

*** server vm
这个报错的原因就是 elasticsearch 期望自己是运行在 jvm server 模式下的

#+BEGIN_QUOTE
JVM Server模式与client模式启动，最主要的差别在于：-Server模式启动时，速度较慢，但是一旦运行起来后，性能将会有很大的提升.原因是:

当虚拟机运行在-client模式的时候,使用的是一个代号为C1的轻量级编译器, 而-server模式启动的虚拟机采用相对重量级,代号为C2的编译器. C2比C1编译器编译的相对彻底,,服务起来之后,性能更高.
#+END_QUOTE

这个解决办法是在 =config/jvm.options= 中加上 

#+BEGIN_SRC
-server
#+END_SRC

这个参数

*** vm.max_map_count
还需要解决一个问题，就是 elasticsearch 教程到处都会将的 vm.max_map_count，这个又是一个命令解决


#+BEGIN_SRC bash
sysctl -w vm.max_map_count=262144
#+END_SRC

* 运行成功

修改了一系列的参数之后，elasticsearch 终于在树莓派上运行了起来

* 性能不足

刚开始运行的时候，树莓派上的 elasticsearch 表现的还可以，很快就把其它节点上的数据给同步了，但是我在用 kibana 的时候，基本上很多查询都会报 timeout 错误，而且反应非常慢，而我自己把树莓派的 elasticsearch 停了之后，一切都恢复了，看来树莓派这种 arm 小鸡运行 elasticsearch 还是不行


